//
//  FHSyncUtilsTest.m
//  fh-ios-sdk
//
//  Copyright (c) 2012-2015 FeedHenry. All rights reserved.
//

#import "FHSyncUtilsTest.h"
#import "FHSyncUtils.h"
#import "FHJSON.h"

@implementation FHSyncUtilsTest

- (void)setUp {
    [super setUp];
}

- (void)tearDown {
    [super tearDown];
}

- (void)testGetStorageFilePath {
    NSString *fileName = @".test.sync.json";
    NSString *filePath = [FHSyncUtils getStorageFilePath:fileName];
    XCTAssertTrue([[filePath lastPathComponent] isEqualToString:fileName],
                  @"filePath is wrong: path = %@", filePath);
}

- (void)testSaveAndLoadData {
    NSString *fileName = @".test.sync.json";
    NSMutableDictionary *data = [NSMutableDictionary dictionary];
    data[@"test1"] = @"test1";
    data[@"test2"] = @"test2";
    NSError *error = nil;
    [FHSyncUtils saveData:[data JSONString] toFile:fileName backup:NO error:error];
    XCTAssertNil(error, @"Error when saving data: %@", [error localizedDescription]);
    error = nil;
    NSString *dataContent = [FHSyncUtils loadDataFromFile:fileName error:error];
    XCTAssertNil(error, @"Error when loading data: %@", [error localizedDescription]);
    NSDictionary *dataLoaded = [dataContent objectFromJSONString];
    NSString *test1Data = dataLoaded[@"test1"];
    NSString *test2Data = dataLoaded[@"test2"];
    XCTAssertTrue([test1Data isEqualToString:@"test1"], @"test1 data match");
    XCTAssertTrue([test2Data isEqualToString:@"test2"], @"test2 data match");
}

- (void)testHashValue {
    NSString *text = @"test";
    NSString *hashValue = [FHSyncUtils generateHashWithString:text];
    NSLog(@"generate hashValue is %@", hashValue);
    NSString *expected = @"a94a8fe5ccb19ba61c4c0873d391e987982fbbd3";
    XCTAssertTrue([hashValue isEqualToString:expected], @"SHA1 hash value doesn't match");
}

- (void)testGenerateHash {
    NSMutableDictionary *data = [NSMutableDictionary dictionary];
    data[@"testKey"] = @"Test Data";
    data[@"testBoolKey"] = @YES;
    data[@"testNumKey"] = @10;
    NSMutableArray *array = [NSMutableArray array];
    [array addObject:@"obj1"];
    [array addObject:@"obj2"];
    data[@"testArrayKey"] = array;
    NSMutableDictionary *dict = [NSMutableDictionary dictionary];
    dict[@"obj3key"] = @"obj3";
    dict[@"obj4key"] = @"obj4";
    data[@"testDictKey"] = dict;
    NSLog(@"Data = %@", [data JSONString]);
    NSString *hashValue = [FHSyncUtils generateHashForData:data];
    NSString *expectedHashValue =
        @"5f4675723d658919ede35fac62fade8c6397df1d"; // This value is generated
                                                     // by running the generate
                                                     // hash function against
                                                     // the exactly same JSON
                                                     // object in the Javascript
                                                     // SDK
    NSLog(@"Generated hashValue is %@", hashValue);
    XCTAssertNotNil(hashValue, @"Hash value should not be nil");
    XCTAssertTrue([hashValue isEqualToString:expectedHashValue],
                  @"Hashvalue generated by ios SDK doesn't match JS SDK. ios = " @"%@ :: js = %@",
                  hashValue, expectedHashValue);
}

@end
